version: "3"

services:

  mysql-server:
    container_name: mysql-server
    hostname: mysql-server
    image: mysql-server
    volumes:
      - mysql-data:/var/lib/mysql
    build: mysql-server/
    tty: true
    networks:
      - my-net

  flask-app:
    container_name: flask-app
    hostname: flask-app
    image: flask-app
    build: flask-app/
    networks:
      - my-net
    depends_on:
      - mysql-server

networks:
  my-net:
    external: true

volumes:
  mysql-data: